version: "3.9"

services:
  postgres:
    image: postgres:15
    container_name: divvy_postgres
    restart: always
    environment:
      POSTGRES_DB: divvy
      POSTGRES_USER: divvy_user
      POSTGRES_PASSWORD: divvy_password
    ports:
      - "5000:5000"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ../sql:/docker-entrypoint-initdb.d
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U divvy_user -d divvy" ]
      interval: 10s
      timeout: 5s
      retries: 5

  pgadmin:
    image: dpage/pgadmin4
    container_name: divvy_pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@divvy.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      postgres:
        condition: service_healthy

volumes:
  postgres_data:
